apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-custom-target-revision
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - path: examples/custom-target-revision/resources
      repoURL: https://github.com/dag-andersen/argocd-diff-preview
      targetRevision: example-redirect-tag