name: Generate Diff

on:
  # Triggers the workflow on  pull request events but only for the "main" branch
  
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      

jobs:
  render-diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: pull-request

      - uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: NCTL-scan-installer
        uses: supplypike/setup-bin@v4
        with:
          uri: 'https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.4.2/nctl_4.4.2_linux_386.zip'
          name: 'nctl'
          version: '4.4.2'

      - name: Generate Diff
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/main:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -e TARGET_BRANCH=${{ github.head_ref }} \
            -e REPO=${{ github.repository }} \
            dagandersen/argocd-diff-preview:v0.0.35
            
          #cat output/diff.md
          echo "Updated yaml" 
          cat ./output/target/nginx-ingress

      - name: Run scan
        run: |
          pwd
          nctl scan kubernetes -p main/policy-scan -r ./output/target/nginx-ingress --details 
          # --audit-as-warn
          echo "nctl Scan completed"

      - name: Post diff as comment
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md --edit-last || \
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
